version: '3.9'

services:
  dev:
    container_name: KBTG_Test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3015:3015"      
    volumes:
      - ./src:/app/src
    networks:
      - sale_net
    command: uvicorn api:app --host 0.0.0.0 --port 3015 --reload
    restart: unless-stopped
networks:
  sale_net:
    driver: bridge
