version: '3.9'

services:
  dev:
    container_name: KBTG_Test_HR_agent
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3016:3016"      
    volumes:
      - ./src:/app/src
    networks:
      - sale_net
    command: uvicorn api:app --host 0.0.0.0 --port 3016 --reload
    restart: unless-stopped
networks:
  sale_net:
    driver: bridge
